%%{init: {'theme': 'base'}}%%
graph TD
    IA["Inteligencia Artificial"]
    ML["Machine Learning"]
    DL["Deep Learning"]
    DS["Ciencia de Datos"]

    IA --> ML
    ML --> DL
    IA -.->|"se apoya en"| DS
